### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by carlosgarridoaptoide**

### CODE REVIEW

**Review by rodolfobcardoso — APPROVED** [review]

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by cumcum8197** [comment]
a31f352e8682fdf2aa194905ea1503cd9a83564e

**Comment by cumcum8197** [comment]
5b538ad60a5a1404088fe3bd298650a9f0726140

**Comment by cumcum8197** [comment]
e2bdc006abd0fd93d665a3aabe24ef61c1e90aed

**Comment by cumcum8197** [comment]
3ea96ad0d2e2591d2d1d3ecf4a77073fea3e5597

**Comment by cumcum8197** [comment]
05538d490b21a47e944ba4157de033f5e27c8a94

**Comment by cumcum8197** [comment]
8c8194365c9376d31a470a11fb5121b286362203

**Comment by cumcum8197** [comment]
350541c6f3c20d86f8ca805461b1b44bf04516f8

**Comment by cumcum8197** [comment]
fc589bd5bcca551c3969792904cc20ba1bac5f86

**Comment by cumcum8197** [comment]
ffabadcb1b7a68f0a52f04227ceed845c8bb8b19

**Comment by cumcum8197** [comment]
ed4395016c57f5100f29895050997e5b74c3d3cb

**Comment by cumcum8197** [comment]
ec42cebfe8f61cb03682f1325e33292706c5d4f0

**Pull request merged**
