### PR TITLE
New Crowdin updates

### PR DESCRIPTION
**Pull request by carlosgarridoaptoide**

### CODE REVIEW

**Comment by catappult-codebuilder-dev2** [comment]
Build started for merge commit.

**Comment by catappult-codebuilder-dev2** [comment]
Build finished.

**Comment by catappult-codebuilder-dev2** [comment]
Build started for merge commit.

**Comment by catappult-codebuilder-dev2** [comment]
Build finished.

**Review by rodolfobcardoso — APPROVED** [review]

**Comment by giovanni-aptoide** [comment]
Can we close this PR?

**Review by rodolfobcardoso — APPROVED** [review]

**Pull request merged**
