### PR TITLE
[APPC-2389] initial commit

### PR DESCRIPTION
**Pull request by Emadeg**
`**What` does this PR do?**

   A few sentences describing the overall goals of the pull request's commits.

   Explain any technical decisions that were made and why (when it makes sense).

**Database changed?**

   Yes | No

**Where should the reviewer start?**

- [x] Foo.java
- [x] Foo.kt

**How should this be manually tested?**

  Flow on how to test this.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-XXXX](https://aptoide.atlassian.net/browse/APPC-XXXX)

**Code Review Checklist**

- [x] Architecture
- [x] Documentation on public interfaces
- [x] Database changed?
- [x] Database migration (if applicable)?
- [x] Remove comments & unused code & forgotten testing Logs
- [x] Codestyle
- [x] Functional QA tests pass

### CODE REVIEW

**Comment by catappult-codebuilder-dev2** [comment]
Can one of the admins verify this patch?

**Comment by Emadeg** [comment]
0x8a2d7371dbe209914b9ad982e5d22444a293e3cf

**Comment by G0retZ** [comment]
Hello guys!
3 things here:
1. What is this patch about? Description is missing.
2. It has conflicts that should be resolved before review
3. It should point not to `master` but to `dev` instead. As it should be tested before release.
Thanks.

**Comment by G0retZ** [comment]
If no one will answer till Monday, this will be closed and marked as spam.

**Comment by Emadeg** [comment]
e7c64764-0a61-4032-bb83-8ea06bf7838a

**Comment by Emadeg** [comment]
0xa9357627d2930db409cbcfaf64394a925cb104a691573d91bc5421aa5854ed7e

**Comment by Emadeg** [comment]
``

**Comment by Emadeg** [comment]
https://play.google.com/store/apps/details?id=com.yalla.yallagames

**Comment by Emadeg** [comment]
e7c64764-0a61-4032-bb83-8ea06bf7838a

**Comment by Emadeg** [comment]
0xa9357627d2930db409cbcfaf64394a925cb104a60x757fa79e15873c5e0889d05f4721196ed5517418

**Comment by Emadeg** [comment]
[YallaLudo] 952274 is your verification code, please don't provide it to others. After unbinding, you cannot log in to the app with this phone number.

**Pull request closed without merging**
