### PR TITLE
[APPC-4447] Update sentry

### PR DESCRIPTION
**Pull request by ricardo-frango**
**What does this PR do?**

   Update Sentry lib

**Database changed?**

   No

**Where should the reviewer start?**

- [ ] libs.versions.toml
- [ ] .gitignore
- [ ] gradle.properties
- [ ] AndroidManifest.xml
- [ ] build.gradle.kts
- [ ] InitilizeDataAnalytics.kt
- [ ] SentryReceiver.kt
- [ ] data_extraction_rules.xml
- [ ] SentryAnalytics.kt
- [ ] SentryEventLogger.kt
- [ ] BuildConfigExtension.kt

**How should this be manually tested?**

  Start the app. Check if sentry is sending analytics.

**What are the relevant tickets?**

  Tickets related to this pull-request: [APPC-4447](https://aptoide.atlassian.net/browse/APPC-4447)

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

[APPC-4447]: https://aptoide.atlassian.net/browse/APPC-4447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by rodolfobcardoso — APPROVED** [review]

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by cumcum8197** [comment]
f0d73a4a0642a372d4530c3216a33ed0d8cba8a6

**Comment by cumcum8197** [comment]
1e975ecf294f24b4a01fb7e84613ed7941b4c5a7

**Comment by cumcum8197** [comment]
292e72a45881a4ed78a46bb0d16d224150debb71

**Pull request merged**
