### PR TITLE
[APPC-4187] Multiple Cards: Processing result

### PR DESCRIPTION
**Pull request by rodolfobcardoso**
**What does this PR do?**
Processing result from success, fail, redirect, 3DS

**Database changed?**
No

**Code Review Checklist**

- [ ] Architecture
- [ ] Documentation on public interfaces
- [ ] Database changed?
- [ ] Database migration (if applicable)?
- [ ] Remove comments & unused code & forgotten testing Logs
- [ ] Codestyle
- [ ] Functional QA tests pass

### CODE REVIEW

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Comment by rodolfobcardoso** [comment]
run-jenkins-build

**Review by gustavoaptoide — APPROVED** [review]

**Pull request merged**
